name = "merch-backend"
main = "src/index.ts"
compatibility_date = "2025-11-15"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "merch-db"
database_id = "3967b160-494c-48f1-bb65-8f6861cbea2e"